version: '3.4'

services:
  rest-api:
    image: ${DOCKER_REGISTRY-}rest-api
    build:
      context: .
      dockerfile: src/MinimalApiTemplate.REST/Dockerfile
    ports:
      - "5000:8080"
      - "5001:8081"
  sql-server-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "Password1!"
      ACCEPT_EULA: "Y"
    volumes:
      - ./VolumeData/SqlServer/data:/var/opt/mssql/data
  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 8081:80
#if (RabbitMQ)
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 8082:15672
#endif